name: computer-vision-mia
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2
  - matplotlib
  - pillow
  - opencv
  - pytorch
  - torchvision
  - jupyterlab
  - notebook
  - ipykernel
